application: kenix-www
api_version: 1
runtime: python27
threadsafe: true
version: 1

env_variables:
  DJANGO_SETTINGS_MODULE: 'kenix.settings'

builtins:
- deferred: on
- remote_api: on

handlers:
- url: /_ah/spi/.*
  script: spi.application

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /.*
  script: wsgi.application

libraries:
- name: pycrypto
  version: latest
- name: endpoints
  version: latest
- name: django
  version: "1.5"
- name: PIL
  version: 1.1.7