application: kenix-www
api_version: 1
runtime: python27
threadsafe: true
version: 1

env_variables:
  DJANGO_SETTINGS_MODULE: 'www.settings'

builtins:
- deferred: on
- remote_api: on

handlers:
- url: /.*
  script: www.wsgi.app

libraries:
- name: django
  version: "1.5"
